# Generated by Django 4.2.1 on 2023-09-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_alter_feature_options_alter_town_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentfeature',
            name='feature',
        ),
        migrations.AddField(
            model_name='apartmentfeature',
            name='feature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Rental.feature'),
        ),
    ]
