# Generated by Django 4.2.1 on 2023-09-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0003_remove_apartmentfeature_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='apartments',
        ),
        migrations.AddField(
            model_name='apartment',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='Rental.town'),
        ),
    ]
