# Generated by Django 4.2.1 on 2023-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0005_alter_type_apartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='occupants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
