# Generated by Django 4.2.1 on 2023-09-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0006_apartment_occupants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='apartments',
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Rental.type'),
        ),
    ]
